"""
Game settings

"""

# general configuration
GAME_TITLE = "KNIGHT, THIEFS AND WIZARDS GAME"

# initial settings
INITIAL_PLAYER_HEALTH = 5
INITIAL_ENEMY_LEVEL = 1

# score assignment options
SCORE_SUCCESS_ATTACK = 1
SCORE_ENEMY_DOWN = 5

# messages
MSG_SUCCESS_ATTACK = "YOUR ATTACK IS SUCCESSFUL!"
MSG_SUCCESS_DEFENCE = "YOUR DEFENCE IS SUCCESSFUL!"
MSG_FAILURE_ATTACK = "YOUR ATTACK IS FAILED!"
MSG_FAILURE_DEFENCE = "YOUR DEFENCE HAS BEEN BREACHED!"
MSG_DRAW = "IT'S A DRAW!"
